### ISSUE TITLE
[BUG]Slime poly crystals add to a stack even if the stack is maxed

### ISSUE THREAD

**Issue by MaltVinegar** [SinguloStation13/SinguloStation13-Archived#27]
## Reproduction:

Get a full stack of some material, use the slime polycrystal on the stack, you now have a stack with an amount higher than 50.

**Comment by ISOSS13** [comment]
**[Unintended Feature] TLDR; I didn't see bug in the title, and thought it was a proposed feature, I vote we don't remove it unless combat is planned to happen more often in the future** Does it affect the game in a negative way (legitimate question)? We already have trash bags of holding in a BoH for almost unlimited space, you could even use multiple polycrystals on one stack (assuming this works) and get an incredibly high stacked material stack, I don't think this makes anything unbalanced because we are a construction server. To me it feels like a convenience that requires a bit of effort to get working in the first place, like Pluxiom internals. Although if antagonists or combat is planned/going to become more often in the future then I would change my vote to no but as it stands it's a pretty neat thing, but only the host would know that.

**Comment by KubeRoot** [comment]
> We already have trash bags of holding in a BoH for almost unlimited space

I believe trashbags of holding don't have nearly as much storage on the rebase. The trashbags on bee had high storage (at the time pre-rebase singulo was forked), because an admin item was miscoded to override the trashbags of holding, drastically increasing weight class, maximum combined weight *and* maximum items stored.
That said, I think we need some alternative for the amount of materials you could store pre-rebase, but that's a known matter that should probably be discussed outside of this issue.

**Comment by MaltVinegar** [comment]
> That said, I think we need some alternative for the amount of materials you could store pre-rebase, but that's a known matter that should probably be discussed outside of this issue.

I wouldn't be opposed to adding materials to the list of items construction bags can hold and upping the size of what can be held in them

**Comment by ZombieNub** [comment]
Simply for the sake of learning SS13 programming, I will attempt to fix this issue.

**Comment by KubeRoot** [comment]
The PR fixing this issue was merged, should it be closed?

**Comment by Urumasi** [comment]
> The PR fixing this issue was merged, should it be closed?

Correct
